---
title: "Starbucks Location in the Great Britain Interactive Map with Leaflet"
author: "Abdelrahman"
output: html_document
---

<style>
.leaflet {
    margin: auto;
}
</style>

## Load Libraries

```{r libraries, message=FALSE, warning=FALSE}
library(leaflet)
library(data.table)
library(dplyr)
```

## Get the data
```{r}
url <- "https://raw.githubusercontent.com/chrismeller/StarbucksLocations/master/stores.csv"
starbucks <- fread(url)
table(starbucks$CountryCode)
```

```{r, comment = ""}
starbucks %>%
    names()
```

Since I'm only plotting starbucks locations in the GB, I will be filtering the data based on the country. Also, I only require the name, longitude and latitude, so I'll be using dplyr to select the columns, and then rename the lat and long columns. 

## Data Preprocessing
```{r}
sb_loc <- starbucks %>% 
    filter(CountryCode == "GB") %>% 
    select(Latitude, Longitude, Name) %>% 
    rename(lat = Latitude, lng = Longitude)
```

## Creating the map

```{r, fig.align="center", fig.width=8, fig.height=6}
m <- leaflet(sb_loc) %>%
    addProviderTiles(providers$Esri.NatGeoWorldMap) %>%
    addCircleMarkers(
        ~ lng,
        ~ lat,
        popup = sb_loc$Name,
        weight = 2,
        radius = 3,
        stroke = F,
        fillOpacity = 0.5,
        clusterOptions = markerClusterOptions()
    )
m
```

